// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecettesAPI_HBKMAM.Data;

#nullable disable

namespace RecettesAPI_HBKMAM.Migrations
{
    [DbContext(typeof(RecettesAPIContext))]
    [Migration("20240122085909_newCreation")]
    partial class newCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Categorie", b =>
                {
                    b.Property<int>("Id_categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_categorie"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_categorie");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Ingredient", b =>
                {
                    b.Property<int>("ingredient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ingredient_id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ingredient_id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Recipe", b =>
                {
                    b.Property<int>("recipe_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("recipe_id"));

                    b.Property<int>("CategorieId_categorie")
                        .HasColumnType("integer");

                    b.Property<int>("category_id")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("photos_array")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("time")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("recipe_id");

                    b.HasIndex("CategorieId_categorie");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("recipe_id")
                        .HasColumnType("integer");

                    b.Property<int>("ingredient_id")
                        .HasColumnType("integer");

                    b.Property<string>("ingredient_quantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("recipe_id", "ingredient_id");

                    b.HasIndex("ingredient_id");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Recipe", b =>
                {
                    b.HasOne("RecettesAPI_HBKMAM.Models.Categorie", "Categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId_categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.RecipeIngredient", b =>
                {
                    b.HasOne("RecettesAPI_HBKMAM.Models.Ingredient", "ingredient")
                        .WithMany("recipe_ingredients")
                        .HasForeignKey("ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecettesAPI_HBKMAM.Models.Recipe", "recipe")
                        .WithMany("recipe_ingredients")
                        .HasForeignKey("recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingredient");

                    b.Navigation("recipe");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Ingredient", b =>
                {
                    b.Navigation("recipe_ingredients");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Recipe", b =>
                {
                    b.Navigation("recipe_ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
