// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecettesAPI_HBKMAM.Data;

#nullable disable

namespace RecettesAPI_HBKMAM.Migrations
{
    [DbContext(typeof(RecettesAPIContext))]
    partial class RecettesAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Categorie", b =>
                {
                    b.Property<int>("Id_categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_categorie"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_categorie");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Ingredient", b =>
                {
                    b.Property<int>("Id_Ingredient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ingredient"));

                    b.Property<string>("Ingredient_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo_url_ingredient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Ingredient");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.IngredientAmount", b =>
                {
                    b.Property<int>("Id_IngredientRecipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_IngredientRecipe"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Ingredient")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Recipe")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId_Recipe")
                        .HasColumnType("integer");

                    b.HasKey("Id_IngredientRecipe");

                    b.HasIndex("RecipeId_Recipe");

                    b.ToTable("IngredientAmount");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Recipe", b =>
                {
                    b.Property<int>("Id_Recipe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Recipe"));

                    b.Property<DateTime>("Created_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_categorie")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Photo_array")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Photo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Recipe");

                    b.ToTable("Recette");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.IngredientAmount", b =>
                {
                    b.HasOne("RecettesAPI_HBKMAM.Models.Recipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId_Recipe");
                });

            modelBuilder.Entity("RecettesAPI_HBKMAM.Models.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
